project:
  type: website
  output-dir: docs
website:
  title: "Narayani Vedam"
  site-url: https://www.narayanivedam.github.io/docs/
  description: "My academic website"

  navbar:
    left:
    - text: Course
      href: course.qmd
    - text: Teaching
      href: teaching.qmd
    - text: Research
      href: about.qmd
    right:
    - icon: ai-google-scholar ai
      text: Google Scholar
      href: https://scholar.google.com/citations?user=8Wxq4kIAAAAJ&hl=en&inst=3212728378801010220&oi=ao
    - icon: github
      text: Github
      href: https://github.com/NV2019
    - icon: twitter
      text: Twitter
      href: https://twitter.com/ennnvvy
    - icon: linkedin
      text: Linkedin
      href: https://www.linkedin.com/in/narayani-vedam-9135a1185/
    - icon: envelope
      text: Contact me
      href: mailto:nvedam@nus.edu.sg

  page-footer:
    right: "Narayani Vedam, 2023."
format:
  html:
    twitter-card:
      creator: "@ennnvvy"
      image: "images/profile.png"
      card-style: summary_large_image
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1em
    theme: spacelab
    css: "style.css"